### PR TITLE
Add a new context processor to determine if a UA is mobile

### PR DESCRIPTION
**Pull request by javierhdez3**
Hello Greg, 

First of all, thank you for taking time to make this project because it simplifies a lot things.

Let's get started.

What I propose is to add a new context processor that indicates if the request is made by a mobile user agent. Right now there is no way to know this from a template.

This makes sense in case we want to show a way to get back to mobile flavour once we have selected the full one.

Again, thank you for your time and work. Let me know what you think.

Cheers.

Javi

### CODE REVIEW

**Comment by tysonclugg** [comment]
Looks like the build failed due to a pypi outage - can someone please hit the `Rebuild` button on https://travis-ci.org/gregmuellegger/django-mobile/jobs/25143386 so this PR can move towards being accepted?

**Comment by gregmuellegger** [comment]
@tysonclugg I regenerated the build, but it doesn't run through. I haven't look into this PR so far. Sorry @javierhdez3, it slipped through my attention.

Do you still have interest in this? If so post here and I will reopen the PR.

**Comment by tysonclugg** [comment]
Hi @gregmuellegger - We've been using these patches in production for a long time, it'd be awesome if they are included in the upcoming 0.7.0 release.  Thanks!

**Comment by tysonclugg** [comment]
@javierhdez3 - can you please rebase your branch against the current master, and force push the resulting commits to your branch?

**Comment by gregmuellegger** [comment]
@tysonclugg You could re-create a new PR based on this one.

**Pull request closed without merging**
